// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dnd_infra;

#nullable disable

namespace dnd_infra.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    [Migration("20230409152228_SeedArtefacts")]
    partial class SeedArtefacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dnd_infra.Items.DALs.ArtefactDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CastDieToDiscardAfterUsage")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DiscardAfterUsage")
                        .HasColumnType("bit");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artefacts", "Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CastDieToDiscardAfterUsage = false,
                            Description = "Couverte de symboles magiques.",
                            DiscardAfterUsage = false,
                            Explanation = "Quand vous ouvrez un coffre, vous pouvez garder l'objet trouvé, ou vous en défausser et en choisir un autre.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Amulette de Yondalla"
                        },
                        new
                        {
                            Id = 2,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Des runes de protection sont serties dans sa pierre.",
                            DiscardAfterUsage = false,
                            Explanation = "Quand vous ouvrez un coffre, vous avez le choix entre 4 objets. Choisissez en deux que vous gardez. Par ailleurs, les pièges ne vous infligent pas de dégât. Après avoir fait votre choix, lancez le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 3,
                            Name = "Fortune de Yondalla"
                        },
                        new
                        {
                            Id = 3,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Passez cet anneau à votre doigt pour disparaître dans les ténèbres du donjon.",
                            DiscardAfterUsage = false,
                            Explanation = "Déplacez vous où vous le désirez dans la pièce sans être détecté. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Anneau des ombres"
                        },
                        new
                        {
                            Id = 4,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Composée de l'écorce des arbres magiques de Arnholm, cette cape légère vous protège.",
                            DiscardAfterUsage = false,
                            Explanation = "Portez cette cape pour ne pas subir de dégâts lors d'une attaque ou d'un événement. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Cape en peau d'écorce"
                        },
                        new
                        {
                            Id = 5,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Forgé dans un moment de rage par les nains, ce bouclier agit de manière imprévisible.",
                            DiscardAfterUsage = false,
                            Explanation = "Redirigez les dégâts que vous devez subir sur les points de vie d'un autre héros. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 2,
                            Name = "Bouclier du chaos"
                        },
                        new
                        {
                            Id = 6,
                            CastDieToDiscardAfterUsage = false,
                            Description = "Elle renferme la sagesse de nombreux anciens.",
                            DiscardAfterUsage = false,
                            Explanation = "Permet au porteur de chercher des pièges dans la salle.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Amulette d'Olidammara"
                        },
                        new
                        {
                            Id = 7,
                            CastDieToDiscardAfterUsage = false,
                            Description = "Il appartenait autrefois à de sages seigneurs à qui il offrait ses dons de vision.",
                            DiscardAfterUsage = true,
                            Explanation = "Révelez tous les pièges dans la pièce. L'artefact disparaît après son utilisation.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Orbe de vision lucide"
                        },
                        new
                        {
                            Id = 8,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Découvert au fond d'une fontaine elfe, il réfléchit l'image de tout ce qu'il voit.",
                            DiscardAfterUsage = false,
                            Explanation = "L'attaquant subit les dégâts du jet de dé à votre place. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 3,
                            Name = "Bouclier miroir elfe"
                        },
                        new
                        {
                            Id = 9,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Les enchantements tissés dans cette cape permettent d'absorber les attaques physiques.",
                            DiscardAfterUsage = false,
                            Explanation = "Augmente la classe d'armure de 1 pour ce tour. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Cape de Boccob"
                        },
                        new
                        {
                            Id = 10,
                            CastDieToDiscardAfterUsage = true,
                            Description = "Soufflez fort pour appeler de l'aide.",
                            DiscardAfterUsage = false,
                            Explanation = "Déplacez n'importe quel héros sur une case près de vous. Lancez ensuite le dé de hasard pour savoir si vous gardez ou non l'artefact.",
                            ImageUrl = "",
                            Level = 1,
                            Name = "Cor de l'invocateur"
                        });
                });

            modelBuilder.Entity("dnd_infra.Items.DALs.ArtefactEffectDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtefactId")
                        .HasColumnType("int");

                    b.Property<bool?>("CanCastTrapFinderDie")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanDiscardChestItemToPickAnotherOneOneTime")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanDiscardChestItemToPickAnotherOneThreeTimes")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanDiscardChestItemToPickAnotherOneTwoTimes")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanInvokeHeroNearBy")
                        .HasColumnType("bit");

                    b.Property<bool?>("DismissAllAttacks")
                        .HasColumnType("bit");

                    b.Property<int?>("FootStepsDecrease")
                        .HasColumnType("int");

                    b.Property<int?>("FootStepsIncrease")
                        .HasColumnType("int");

                    b.Property<bool?>("IsUndetectableInNextRound")
                        .HasColumnType("bit");

                    b.Property<int?>("LifeDecrease")
                        .HasColumnType("int");

                    b.Property<int?>("LifeIncrease")
                        .HasColumnType("int");

                    b.Property<int?>("ManaDecrease")
                        .HasColumnType("int");

                    b.Property<int?>("ManaIncrease")
                        .HasColumnType("int");

                    b.Property<bool?>("NotAffectedByTraps")
                        .HasColumnType("bit");

                    b.Property<bool?>("NotAffectedByTrapsWhilePickingChestItems")
                        .HasColumnType("bit");

                    b.Property<bool?>("PicksTwoOutOfFourChestItems")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReflectsBackToAnotherHero")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReflectsBackToAttacker")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReflectsBackToRandomTarget")
                        .HasColumnType("bit");

                    b.Property<bool?>("RerollDice")
                        .HasColumnType("bit");

                    b.Property<bool?>("RevealRoomTraps")
                        .HasColumnType("bit");

                    b.Property<int?>("ShieldDecrease")
                        .HasColumnType("int");

                    b.Property<int?>("ShieldIncrease")
                        .HasColumnType("int");

                    b.Property<int?>("StorageDecrease")
                        .HasColumnType("int");

                    b.Property<int?>("StorageIncrease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactId");

                    b.ToTable("ArtefactEffects", "Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtefactId = 1,
                            CanDiscardChestItemToPickAnotherOneOneTime = true
                        },
                        new
                        {
                            Id = 2,
                            ArtefactId = 2,
                            PicksTwoOutOfFourChestItems = true
                        },
                        new
                        {
                            Id = 3,
                            ArtefactId = 2,
                            NotAffectedByTrapsWhilePickingChestItems = true
                        },
                        new
                        {
                            Id = 4,
                            ArtefactId = 3,
                            IsUndetectableInNextRound = true
                        },
                        new
                        {
                            Id = 5,
                            ArtefactId = 4,
                            DismissAllAttacks = true
                        },
                        new
                        {
                            Id = 6,
                            ArtefactId = 5,
                            ReflectsBackToAttacker = true
                        },
                        new
                        {
                            Id = 7,
                            ArtefactId = 6,
                            CanCastTrapFinderDie = true
                        },
                        new
                        {
                            Id = 8,
                            ArtefactId = 7,
                            RevealRoomTraps = true
                        },
                        new
                        {
                            Id = 9,
                            ArtefactId = 8,
                            ReflectsBackToAttacker = true
                        },
                        new
                        {
                            Id = 10,
                            ArtefactId = 9,
                            ShieldIncrease = 1
                        },
                        new
                        {
                            Id = 11,
                            ArtefactId = 10,
                            CanInvokeHeroNearBy = true
                        });
                });

            modelBuilder.Entity("dnd_infra.Items.DALs.ArtefactEffectDal", b =>
                {
                    b.HasOne("dnd_infra.Items.DALs.ArtefactDal", null)
                        .WithMany("Effects")
                        .HasForeignKey("ArtefactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Items.DALs.ArtefactDal", b =>
                {
                    b.Navigation("Effects");
                });
#pragma warning restore 612, 618
        }
    }
}
