// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dnd_infra;

#nullable disable

namespace dnd_infra.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    [Migration("20250429155903_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.AdventureDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Adventures", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.RoomDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdventureId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsStartRoom")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.ToTable("Rooms", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.PositionDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SquareId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SquareId")
                        .IsUnique();

                    b.ToTable("Positions", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("HasBottomWall")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasLeftWall")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasLockedChest")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasOpenedChest")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPillar")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasRightWall")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasTopWall")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDoor")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Squares", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareTrapDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SquareId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SquareId")
                        .IsUnique();

                    b.ToTable("SquareTraps", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.CampaignDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DungeonMasterId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMasterId");

                    b.ToTable("Campaigns", "Campaigns");
                });

            modelBuilder.Entity("dnd_infra.GameFlow.DALs.CurrentPlayerDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdventureId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("CurrentPlayers", "GameFlow");
                });

            modelBuilder.Entity("dnd_infra.GameFlow.DALs.TurnOrderDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdventureId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TurnOrders", "GameFlow");
                });

            modelBuilder.Entity("dnd_infra.Items.StoredItemDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEquiped")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("StoredItems", "Items");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerAttributesDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChestSearchCount")
                        .HasColumnType("integer");

                    b.Property<int>("FootSteps")
                        .HasColumnType("integer");

                    b.Property<int>("HealCount")
                        .HasColumnType("integer");

                    b.Property<int>("LifePoints")
                        .HasColumnType("integer");

                    b.Property<int>("ManaPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Shield")
                        .HasColumnType("integer");

                    b.Property<int>("TrapSearchCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerAttributes", "Players");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<int?>("SquareId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SquareId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Players", "Players");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerMaxAttributesDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAttackCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxChestSearchCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFootSteps")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLifePoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaxManaPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaxShield")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTrapSearchCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerMaxAttributes", "Players");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerProfileDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles", "Players");
                });

            modelBuilder.Entity("dnd_infra.Users.UserDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ResetTokenExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "Users");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.AdventureDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.CampaignDal", null)
                        .WithMany("Adventures")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.RoomDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.AdventureDal", null)
                        .WithMany("Rooms")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.PositionDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", null)
                        .WithOne("Position")
                        .HasForeignKey("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.PositionDal", "SquareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.Rooms.RoomDal", null)
                        .WithMany("Squares")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareTrapDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", null)
                        .WithOne("Trap")
                        .HasForeignKey("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareTrapDal", "SquareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.CampaignDal", b =>
                {
                    b.HasOne("dnd_infra.Users.UserDal", null)
                        .WithMany()
                        .HasForeignKey("DungeonMasterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("dnd_infra.GameFlow.DALs.CurrentPlayerDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.AdventureDal", null)
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", "Player")
                        .WithOne()
                        .HasForeignKey("dnd_infra.GameFlow.DALs.CurrentPlayerDal", "PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dnd_infra.GameFlow.DALs.TurnOrderDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.Adventures.AdventureDal", null)
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", null)
                        .WithOne("TurnOrder")
                        .HasForeignKey("dnd_infra.GameFlow.DALs.TurnOrderDal", "PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Items.StoredItemDal", b =>
                {
                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", null)
                        .WithMany("StoredItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerAttributesDal", b =>
                {
                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", null)
                        .WithOne("Attributes")
                        .HasForeignKey("dnd_infra.Players.DALs.PlayerAttributesDal", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerDal", b =>
                {
                    b.HasOne("dnd_infra.Campaigns.CampaignDal", null)
                        .WithMany("Players")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", "Square")
                        .WithOne()
                        .HasForeignKey("dnd_infra.Players.DALs.PlayerDal", "SquareId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("dnd_infra.Users.UserDal", null)
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Square");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerMaxAttributesDal", b =>
                {
                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", null)
                        .WithOne("MaxAttributes")
                        .HasForeignKey("dnd_infra.Players.DALs.PlayerMaxAttributesDal", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerProfileDal", b =>
                {
                    b.HasOne("dnd_infra.Players.DALs.PlayerDal", null)
                        .WithOne("Profile")
                        .HasForeignKey("dnd_infra.Players.DALs.PlayerProfileDal", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.AdventureDal", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.RoomDal", b =>
                {
                    b.Navigation("Squares");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.Adventures.Rooms.Squares.DALs.SquareDal", b =>
                {
                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Trap");
                });

            modelBuilder.Entity("dnd_infra.Campaigns.CampaignDal", b =>
                {
                    b.Navigation("Adventures");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("dnd_infra.Players.DALs.PlayerDal", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("MaxAttributes")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("StoredItems");

                    b.Navigation("TurnOrder");
                });

            modelBuilder.Entity("dnd_infra.Users.UserDal", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
